### ISSUE TITLE
TOPIC 1: Object-Oriented Programming - MASTER ISSUE

### ISSUE THREAD

**Issue by alyeffy** [alyeffy/AP-CS-A_2018-2019#1]
### **LAST UPDATED: 12 OCT 2018**
General inquiries and updates relating to **Topic 1** will be updated on this issue.

| **WEEK** | **DATE** | **DETAILS** | **PREP** | **LECTURE NOTES** | **ASSIGNMENT(S)** | **LAB** |
| --- | --- | --- | --- | --- | --- | --- |
| 01 | 05/10/2018 | Intro to the Java language, Object-Oriented Programs, and Basic Program Design Approaches | :x: | [here](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_1/T1-Lesson_01-05102018.md) | :white_check_mark: | :x: |
| 02 | 16/10/2018 | Elementary Java Syntax, Data Representation, and Bit Conversion | :white_check_mark: | [here](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_1/T102-16102018.md) | :x: | :x: |
| 03 | 23/10/2018 | Inheritance and Polymorphism | :x: | [here](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_1/T103-23102018.md) | :white_check_mark: | :white_check_mark: |
| 04 | 30/10/2018 | Abstract Classes, Interfaces, and UML Diagrams | :white_check_mark: | [here](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_1/T104-30102018.md) | :white_check_mark: | :white_check_mark: |

### LESSON 01 - 05/10/2018
Intro to the Java language, Object-Oriented Programs, and Basic Program Design Approaches

**PREP**:
- [x] N/A

**ASSIGNMENTS**:
- [x] If you did the **Pokeball** class definition on paper in class, do the **Trainer** class definition on paper and place it in my pigeonhole before the next class. You can check it against my [Pokeball.java](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_1/T1_code/Pokeball.java) example.
- [x] If you did the **Trainer** class definition on paper in class, do the **Pokeball** class definition on paper and place it in my pigeonhole before the next class. You can check it against my [Trainer.java](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_1/T1_code/Trainer.java) example.
- [x] Make sure you label all the constructors, methods, variables, etc. accordingly (see [Pokemon.java](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_1/T1_code/Pokemon.java) as an example)
- [x] For the [Node.java](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Assignments/topic_1/Node.java) and [Path.java](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Assignments/topic_1/Path.java) classes, follow the **TODO** instructions, e.g. label the types of constructors, methods, variables etc. using the same style as the [Pokemon.java](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_1/T1_code/Pokemon.java) class

**LAB**:
- [x] N/A

---

### LESSON 02 - 16/10/2018
Elementary Java Syntax, Data Representation, and Bit Conversion

**PREP**:
- [x] Follow the instructions in the  [SETUP_and_WORKFLOW.md](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/SETUP_and_WORKFLOW.md) file to set up the development environment and workflow needed for the course. If you encounter any problems along the way, comment below. We will be spending a few minutes at the beginning of the next class going over any setup problems you can't resolve (i.e.**bring your laptop to class**).
- [x] Comment below your **name**, your **favourite food**, and **something you would like to learn how to program** (e.g. a game, a website etc.) (Follow my example comment below).

**ASSIGNMENTS**:
- [x] N/A

**LAB**:
- [x] N/A

---

### LESSON 03 - 23/10/2018
Inheritance and Polymorphism

**PREP**:
- [x] Continue working on any of the Eclipse, GitHub setup etc. and bring any issues you have to class

**ASSIGNMENTS**:
- [x] Read over **Activity 2** of the [Elevens Lab](http://media.collegeboard.com/digitalServices/pdf/ap/elevens-lab-student-guide.pdf)
- [x] Based on what we did for the `Card.java` ([solution](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Labs/Lab_1-Elevens/Solution/Card.java)) class in our first lab last lesson, complete the `isEmpty` and `size` **accessor methods**. HINT: You will need to use one of the methods from the AP Exam [Java Quick Reference](https://secure-media.collegeboard.org/digitalServices/pdf/ap/explore-ap/ap-computer-science-a-2014-java-quick-reference.pdf)

**LAB**:
- [x] [Lab 01](https://github.com/alyeffy/AP-CS-A_2018-2019/tree/master/Labs/Lab_1-Elevens): [Elevens Lab](http://media.collegeboard.com/digitalServices/pdf/ap/elevens-lab-student-guide.pdf) (Activity 1)

---

### LESSON 04 - 30/10/2018
Abstract Classes, Interfaces, and UML Diagrams

**PREP**:
- [x] Review the lecture notes for lessons 1-3 as we will be working on some questions in class

**ASSIGNMENTS**:
- [x] Odd-numbered questions from the **Classes and Objects** MCQ set
- [x] (optional) Even-numbered questions from the **Classes and Objects** MCQ set

**LAB**:
- [x] [Lab 01](https://github.com/alyeffy/AP-CS-A_2018-2019/tree/master/Labs/Lab_1-Elevens): [Elevens Lab](http://media.collegeboard.com/digitalServices/pdf/ap/elevens-lab-student-guide.pdf) (Activity 2)

**Comment by alyeffy** [comment]
I'm **Alyssa**, my favourite food is sushi :sushi: , and I would like to learn how to implement machine learning using [TensorFlow](https://www.tensorflow.org/)!

**Comment by AllenZoo** [comment]
I'm **Allen**, my favourite food is fried chicken and poutine, and I would like to learn how to program a 2D platformer game.

**Comment by alyeffy** [comment]
@AllenZoo @Kevin-Tan25 @RuthlessDebugMachine if you have any questions about assignments, labs, technical issues or general course material for topic 1, you can comment them on this issue thread :)

**Comment by RuthlessDebugMachine** [comment]
Hi Alyssa, I am Howard. I just met a problem. If I want to track 40 previous random number seeds and save them and still updating them while the program is running, can you briefly tell me what the method would be? like the type, brief structure of implements etc. I remember that we seemed have gone over this in class but I did not actually catch on well, thanks!

**Comment by alyeffy** [comment]
Hi @RuthlessDebugMachine, just to clarify, is there a specific way you want to create these random seeds? And as you are updating them, are you simply calling the same random function again to retrieve new values to save to these variables?

**Comment by RuthlessDebugMachine** [comment]
@alyeffy ,yes, by using Math.Random() method, and it is calling the same method again and again.
