### ISSUE TITLE
TOPIC 2: Program Implementation - MASTER ISSUE

### ISSUE THREAD

**Issue by alyeffy** [alyeffy/AP-CS-A_2018-2019#3]
### **LAST UPDATED: 5 DEC 2018**
General inquiries and updates relating to **Topic 2** will be updated on this issue.

| **WEEK** | **DATE** | **DETAILS** | **PREP** | **LECTURE NOTES** | **ASSIGNMENT(S)** | **LAB** |
| --- | --- | --- | --- | --- | --- | --- |
| 05 | 06/11/2018 | Memory Allocation, Operators, and Boolean Expression Evaluation | :x: | [here](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_2/T205-06112018.md) | ✅  | :x: |
| 06 | 13/11/2018 | Control Flow, Scopes, and Iteration | ✅  | [here](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_2/T206-13112018.md) | ✅ | :x: |
| 07 | 20/11/2018 | CANCELLED | ✅ | :x: | ✅ | :x: |
| 08 | 27/11/2018 | Recursion, Implementation Techniques, and I/O | ✅ |  | ✅ | :x: |

### LESSON 05 - 06/11/2018
Memory Allocation, Operators, and Boolean Expression Evaluation

**PREP**:
- [x] N/A

**ASSIGNMENTS**:
- [x] Complete this [Boolean Algebra Design Worksheet](https://docs.google.com/document/d/117Uc4Cxb0RNa0-uS318t7fdx_gDcCaBkZuOEM2YJ99Y/edit?usp=sharing) and place it in my dropbox for next class. Use the examples from the truth tables above as a guide.
- [x] Answers will be posted on the Topic 2 assignment answers [issue](https://github.com/alyeffy/AP-CS-A_2018-2019/issues/5).

**LAB**:
- [x] N/A

---

### LESSON 06 - 13/11/2018
Control Flow, Scopes, and Iteration

**PREP**:
- [x] Review [Lesson 2](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_1/T102-16102018.md) Notes again

**ASSIGNMENTS**:
- [x] From the **Introductory Java Language Features Question Set**, complete questions: 16, 17, 21, 24, 25, 26, and 27.
- [x] Answers will be posted on the Topic 2 assignment answers [issue](https://github.com/alyeffy/AP-CS-A_2018-2019/issues/5).

**LAB**:
- [x] N/A

---

### LESSON 07 - 20/11/2018
CANCELLED due to instructor being sick.

**PREP**:
- [x] Review the [lesson](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_1/T103-23102018.md) on Inheritance and Polymorphism

**ASSIGNMENTS**:
- [x] Complete the Inheritance and Polymorphism MCQ Set
- [x] Answers will be posted on the Topic 1 assignment answers [issue](https://github.com/alyeffy/AP-CS-A_2018-2019/issues/4).

**LAB**:
- [x] N/A

---

### LESSON 08 - 27/11/2018
Recursion, Implementation Techniques, and I/O

**PREP**:
- [x] Review [Lesson 2](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_1/T102-16102018.md) Notes again

**ASSIGNMENTS**:
- [x] Complete the remaining questions in the **Introductory Java Language Features Question Set**
- [x] Complete the **Recursion Question Set**
- [x] Answers will be posted on the Topic 2 assignment answers [issue](https://github.com/alyeffy/AP-CS-A_2018-2019/issues/5).

**LAB**:
- [x] N/A

**Comment by Kevin-Tan25** [comment]
Hey Alyssa,

I hope that you are feeling better.  Where can I find the lesson notes and homework for this week?

**Comment by alyeffy** [comment]
Hi @Kevin-Tan25,
Thank you, I am feeling better :). For the homework I have assigned the Inheritance and Polymorphism question set as a review of Topic 1, since we never really got to working on those questions. There's no rush to complete them before the next lesson, since there are a lot of questions, and it's been a while since we covered it. However, do review the Lesson 2 notes for the next class on Tuesday.

**Comment by Kevin-Tan25** [comment]
@alyeffy 
Sorry for bothering you but do you know where we can find the MCQs?

**Comment by alyeffy** [comment]
@Kevin-Tan25 No problem! I believe I gave that set out along with the the Introductory Java Language Features question set. If not, or if you can't find it, let me know and I'll get another copy of it for you :)

**Comment by Kevin-Tan25** [comment]
Sounds good, thanks!
