### ISSUE TITLE
TOPIC 4: Standard Data Structures - MASTER ISSUE

### ISSUE THREAD

**Issue by alyeffy** [alyeffy/AP-CS-A_2018-2019#9]
### **LAST UPDATED: 20 JAN 2018**
General inquiries and updates relating to **Topic 4** will be updated on this issue.

| **WEEK** | **DATE** | **DETAILS** | **PREP** | **LECTURE NOTES** | **ASSIGNMENT(S)** | **LAB** |
| --- | --- | --- | --- | --- | --- | --- |
| 12 | 08/01/2019 | CANCELLED | ❌ | ❌ | ❌ | ❌ |
| 13 | 14/01/2019 | Object Class, String Class, and Math Class | ❌ | [here](https://github.com/alyeffy/AP-CS-A_2018-2019/blob/master/Lectures/Topic_4/T413-14012019.md) | ✅  | ❌  |
| 14 | 21/01/2019 | Arrays, Array Lists, Collections, and 2-D Arrays | ✅  |  | ✅  | ❌  |
| 15 | 28/01/2019 | AP Lab: Magpie | ✅ | [here](http://media.collegeboard.com/digitalServices/pdf/ap/magpie-lab-student-guide.pdf) | ✅  | ✅ |

---

### LESSON 12 - 08/01/2018
CANCELLED due to instructor unavailability

**PREP**:
- [x] N/A

**ASSIGNMENTS**:
- [x] N/A

**LAB**:
- [x] N/A

---

### LESSON 13 - 14/01/2018
Object Class, String Class, and Math Class

**PREP**:
- [x] N/A

**ASSIGNMENTS**:
- [x] Complete the **Some Standard Classes Question Set**.
- [x] Answers will be posted on the Topic 4 assignment answers [issue](https://github.com/alyeffy/AP-CS-A_2018-2019/issues/10).

**LAB**:
- [x] N/A

---

### LESSON 14 - 21/01/2018
Arrays, Array Lists, Collections, and 2-D Arrays

**PREP**:
- [x] Read notes from last class.

**ASSIGNMENTS**:
- [x] Complete the **Arrays and Array Lists Question Set**.
- [x] Answers will be posted on the Topic 4 assignment answers [issue](https://github.com/alyeffy/AP-CS-A_2018-2019/issues/10).

**LAB**:
- [x] N/A

---

### LESSON 15 - 28/01/2018
AP Computer Science Magpie Lab

**PREP**:
- [x] Read notes from last class.
- [x] Read over [lab guide](http://media.collegeboard.com/digitalServices/pdf/ap/magpie-lab-student-guide.pdf)
- [x] Bring laptop to class and download starter code below

**ASSIGNMENTS**:
- [x] Complete the rest of the Magpie Lab

**LAB**:
- [x] Magpie Lab: [All Activities starter code](https://github.com/alyeffy/AP-CS-A_2018-2019/tree/master/Labs/Lab_2-Magpie)

---
